name: composite actions test

on:
  push:

jobs:
  compoiste-action:
    name: job to test a composite action
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v4
      - uses: ./ # this step to test action file at the root level of our repository 
        id: compositeAction
        with:
          number1: 4
          number2: 2
      - run: echo ${{ steps.compositeAction.outputs.result }}
          
        
  
